version: "3.8"
services:
  proxy:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #app:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
    - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: nameBanner
      MYSQL_USER: al
      MYSQL_PASSWORD: testtest

