spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: al
    password: testtest
    url: "jdbc:mysql://localhost:3306/nameBanner"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
